# Stage 1: Build the application
FROM node:18.19.0-alpine AS builder
WORKDIR /app
COPY . .
COPY package.json package-lock.json ./
RUN apk add --no-cache python3 make g++
ENV PYTHON=python3
RUN npm ci
RUN npm run build

# Stage 2: Production environment
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
