FROM golang:1.21-alpine AS builder

WORKDIR /usr/local/src

RUN apk --no-cache add bash gcc gettext musl-dev

COPY ["go.mod", "go.sum", "./"]
RUN go mod download

COPY . .

RUN go build -o /usr/local/bin/app cmd/main/main.go

FROM alpine AS runner

COPY --from=builder /usr/local/bin/app /usr/local/bin/app
COPY config.yml /config.yml
COPY --from=builder /usr/local/src/internal/contact/mail/template /usr/local/src/internal/contact/mail/template
COPY --from=builder /usr/local/src/internal/order/service/helpers/logo /usr/local/src/internal/order/service/helpers/logo
COPY --from=builder /usr/local/src/internal/order/service/helpers/fonts /usr/local/src/internal/order/service/helpers/fonts

RUN apk --no-cache add ca-certificates

EXPOSE 80
ENTRYPOINT ["/usr/local/bin/app", "--port", "80"]
